server:
  port: 3006
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  application:
    name: message-hub-template
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true


